kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-service
  namespace: test
  labels:
    app: ping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-service
  template:
    metadata:
      labels:
        app: ping-service
    spec:
      containers:
        - name: ping-service
          image: mircocennamo82/my-repo:ping-service
          ports:
            - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: ping-service
  namespace: test
  labels:
    app: ping-service
    spring-boot: "true"
spec:
  selector:
    app: ping-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
