server:
  servlet:
    context-path: /ping
  port: 8080
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  threads:
    virtual:
      enabled: true
  http:
    serviceclient:
      pingpong-service:
        base-url: http://pong-service/  #pong-service is the name of the service in OpenShift, and 8080 is the port exposed by the pong-service
        #base-url: http://localhost:8081/
  application:
    name: ping-service
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      max-lifetime: 1800000
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.h2.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    #username: sa
    #password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


management:
  tracing:
    sampling:
      probability: 1.0
  server:
    port: 8081
  endpoint:
    health:
      probes:
        enabled: true

  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  otlp:
    metrics:
      export:
        enabled: false




logging:
  level:
    application: ${APP_LOG_LEVEL:INFO}
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        org:
          jdbc:
            bind: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: TRACE
